# Generated by Django 3.2.8 on 2023-01-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='published_date',
        ),
    ]
